services:

  laravel_app:
    build:
      context: ./docker/php
    container_name: laravel_container
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - mysql_db
      - redis
    volumes:
      - ./backend:/var/www/

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - laravel_app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/

  mysql_db:
    image: mysql:8.0
    container_name: db_container
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=sKpI@2026
      - MYSQL_DATABASE=skpi
      - MYSQL_USER=root
      - MYSQL_PASSWORD=sKpI@2026
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_container
    restart: unless-stopped
    ports:
      - "5540:5540"

  horizon:
    build:
      context: ./docker/php
    container_name: horizon_container
    command: php artisan horizon
    restart: unless-stopped
    depends_on:
      - laravel_app
      - redis
    volumes:
      - ./backend:/var/www/

  
  scheduler:
    build:
      context: ./docker/php
    container_name: scheduler_container
    command: php artisan schedule:work
    restart: unless-stopped
    depends_on:
      - laravel_app
    volumes:
      - ./backend:/var/www/
  

volumes:
  db_data:
